index:
    path: /
    controller: App\Controller\MainController::indexAction

login:
    path: /login
    controller: App\Controller\LoginController::loginAction

logout:
    path: /logout
    controller: App\Controller\LoginController::logoutAction

character/create:
    path: /character/create
    controller: App\Controller\CharacterController::createAction

character/edit:
    path: /character/edit/{id}
    controller: App\Controller\CharacterController::editAction

character/remove:
    path: /character/remove/{id}
    controller: App\Controller\CharacterController::removeAction

character/list:
    path: /character/list
    controller: App\Controller\CharacterController::listAction

character:
    path: /character/{id}
    controller: App\Controller\CharacterController::showAction